public class Main {
    public static void main(String[] args) {
        // Let's create a Red-Black tree and fill it with some nodes
        RedBlackTree tree = new RedBlackTree();
        System.out.println(tree.insert(7));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");

        System.out.println(tree.insert(3));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(18));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(10));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(22));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(8));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(11));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(26));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(2));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(6));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.insert(13));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");

// Case 1: Deleting a leaf node that is black
        System.out.println(tree.delete(13));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(18));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(11));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(10));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(3));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(7));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(20));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
        System.out.println(tree.delete(8));
        tree.test(tree.root);
        System.out.println(tree.size());
        System.out.println("-----------------------------------------");
    }
}